### ISSUE TITLE
Multiple monitor maximize creates a new workspace even when done on an empty monitor

### ISSUE THREAD

**Issue by riyadh144** [raonetwo/MaximizeToWorkspace#1]
I love your work, I found it yesterday, and it has been working pretty well on one display but on multiple monitors there is that issue.

Now I know that that is partly a problem of gnome itself as it only supports workspaces that span monitors. 
I am not much of a Java Script guy and I don't even know how to try and fix the issue I am having, but I will take a look later

**Comment by raonetwo** [comment]
I will look at it, once I have a second monitor to test and develop with.

**Comment by raonetwo** [comment]
Fixed in the latest revision (10). under review at https://extensions.gnome.org/review/15553. To test it faster install it manually. Closing this.
