### ISSUE TITLE
[Feature Request]: Open a new fullscreen window on the same desktop as the minimized windows

### ISSUE THREAD

**Issue by ivanmood0** [raonetwo/MaximizeToWorkspace#11]
First of all, I want to thank you for the wonderful extension, and also ask if you could add optional support (for example radio switch) so that if all the windows in the current workspace are minimized, open a new fullscreen window on the same desktop. For me, it would be very convenient. And, of course, leave the current option, and in the settings give the ability to choose  users what like best. Thanks for the answer.

**Comment by raonetwo** [comment]
You can fork this repo and add a check for is_minimized, currently not accepting any feature request, try one of the other extensions that are being actively maintained.
