### ISSUE TITLE
Is it possible to go back to previous workspace after the window was closed?

### ISSUE THREAD

**Issue by gapplef** [raonetwo/MaximizeToWorkspace#4]
Thanks for the great extension, the history support really makes a big difference.
A small problem I encountered recently is that after closing the maximized windows, it can not go back to the previous workspace, and I was left with an empty workspace.
So, I wonder if it's possible to go back to previous workspace after the window was closed.

**Comment by raonetwo** [comment]
Hi, Thanks for the feedback.
It should be possible. I intended to do it earlier but at the time I was not able to find the relevant documentation and I did not want to invest too much time into it. 

I will try to look into this next weekend and implement this if I am able to find the relevant documents on how to bind with the close window event. I will also accept any Pull requests if someone creates one that implement this.

**Comment by raonetwo** [comment]
Last commit added this behaviour. I am not really sure if this is the right behaviour to have as it will probably makes sense to just go to the workspace immediately to the left if possible. For now keeping it, maybe this will exposed as a preference sometime in future. Closing this.
