### ISSUE TITLE
Move fullscreen windows to a new workspace too

### ISSUE THREAD

**Issue by sojusnik** [raonetwo/MaximizeToWorkspace#5]
At the moment only maximized windows are moved to a new workspace, but it would be also very helpful if fullscreen windows are moved too.

**Comment by raonetwo** [comment]
Thanks for the feedback,I will look into implementing it. I will also accept Pull Request if someone else is willing to try their hand at this.

**Comment by raonetwo** [comment]
This is done as part of the last commit, closing this.
